global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: 'scrapper'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:8082']
