/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record6<Integer, String, Long, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LINK.LINK</code>.
     */
    public void setLink(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK.LINK</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getLink() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINK.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>LINK.LAST_UPDATED_ID</code>.
     */
    public void setLastUpdatedId(@Nullable String value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINK.LAST_UPDATED_ID</code>.
     */
    @Size(max = 15)
    @Nullable
    public String getLastUpdatedId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LINK.LAST_CHECKED</code>.
     */
    public void setLastChecked(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINK.LAST_CHECKED</code>.
     */
    @Nullable
    public LocalDateTime getLastChecked() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>LINK.LINK_TYPE</code>.
     */
    public void setLinkType(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for <code>LINK.LINK_TYPE</code>.
     */
    @Size(max = 20)
    @Nullable
    public String getLinkType() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row6<Integer, String, Long, String, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row6<Integer, String, Long, String, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.LINK_;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Link.LINK.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return Link.LINK.LAST_UPDATED_ID;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Link.LINK.LAST_CHECKED;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return Link.LINK.LINK_TYPE;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getLink();
    }

    @Override
    @NotNull
    public Long component3() {
        return getChatId();
    }

    @Override
    @Nullable
    public String component4() {
        return getLastUpdatedId();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getLastChecked();
    }

    @Override
    @Nullable
    public String component6() {
        return getLinkType();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getLink();
    }

    @Override
    @NotNull
    public Long value3() {
        return getChatId();
    }

    @Override
    @Nullable
    public String value4() {
        return getLastUpdatedId();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getLastChecked();
    }

    @Override
    @Nullable
    public String value6() {
        return getLinkType();
    }

    @Override
    @NotNull
    public LinkRecord value1(@NotNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull String value) {
        setLink(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@NotNull Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable String value) {
        setLastUpdatedId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable LocalDateTime value) {
        setLastChecked(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable String value) {
        setLinkType(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@NotNull Integer value1, @NotNull String value2, @NotNull Long value3, @Nullable String value4, @Nullable LocalDateTime value5, @Nullable String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "id", "link", "chatId", "lastUpdatedId", "lastChecked", "linkType" })
    public LinkRecord(@NotNull Integer id, @NotNull String link, @NotNull Long chatId, @Nullable String lastUpdatedId, @Nullable LocalDateTime lastChecked, @Nullable String linkType) {
        super(Link.LINK);

        setId(id);
        setLink(link);
        setChatId(chatId);
        setLastUpdatedId(lastUpdatedId);
        setLastChecked(lastChecked);
        setLinkType(linkType);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setLink(value.getLink());
            setChatId(value.getChatId());
            setLastUpdatedId(value.getLastUpdatedId());
            setLastChecked(value.getLastChecked());
            setLinkType(value.getLinkType());
        }
    }
}
