name: Scrapper CI

on:
  push:
    paths:
      - 'scrapper/**'
      - '.github/workflows/scrapper.yml'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check scrapper code style
        run: mvn -pl scrapper -am checkstyle:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - name: Push image to Github Container Registry
        run: |
           docker build -t scrapper_image scrapper
           echo ${{ secrets.PRIVATE_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
           docker tag scrapper_image ghcr.io/arkirka/update_tracker/scrapper_image:latest
           docker push ghcr.io/arkirka/update_tracker/scrapper_image:latest
